# Generated by Django 2.2.1 on 2019-06-01 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20190601_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_num', models.SmallIntegerField(default=0)),
                ('ema_1', models.CharField(default='-,-,-,-,-', max_length=22)),
                ('ema_2', models.CharField(default='-,-,-,-,-,-/-', max_length=22)),
                ('ema_3', models.CharField(default='-,-,-,-,-', max_length=22)),
                ('ema_4', models.CharField(default='-,-,-,-,-', max_length=22)),
                ('ema_5', models.CharField(default='-,-,-,-,-', max_length=22)),
                ('ema_6', models.CharField(default='-,-,-,-,-', max_length=22)),
                ('username', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.Participant')),
            ],
        ),
    ]
