# Generated by Django 2.2.1 on 2019-06-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('phone_num', models.CharField(default='', max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('register_datetime', models.BigIntegerField(blank=True, default=1559382976.184129)),
                ('last_login_datetime', models.BigIntegerField(blank=True, default=1559382976.184129)),
                ('heartbeat_smartwatch', models.BigIntegerField(blank=True, default=1559382976.184129)),
                ('heartbeat_smartphone', models.BigIntegerField(blank=True, default=1559382976.184129)),
            ],
        ),
    ]
