# Generated by Django 2.2.1 on 2019-06-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190601_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='daily_data_size_smartphone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='daily_data_size_smartwatch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='heartbeat_smartphone',
            field=models.BigIntegerField(default=1559633150.645348),
        ),
        migrations.AlterField(
            model_name='participant',
            name='heartbeat_smartwatch',
            field=models.BigIntegerField(default=1559633150.645348),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_login_datetime',
            field=models.BigIntegerField(default=1559633150.644351),
        ),
        migrations.AlterField(
            model_name='participant',
            name='register_datetime',
            field=models.BigIntegerField(default=1559633150.644351),
        ),
    ]
