# Generated by Django 2.2.1 on 2019-06-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190604_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='daily_data_size_smartphone',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='daily_data_size_smartwatch',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='heartbeat_smartphone',
            field=models.BigIntegerField(default=1559636041.312554),
        ),
        migrations.AlterField(
            model_name='participant',
            name='heartbeat_smartwatch',
            field=models.BigIntegerField(default=1559636041.312554),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_login_datetime',
            field=models.BigIntegerField(default=1559636041.312554),
        ),
        migrations.AlterField(
            model_name='participant',
            name='register_datetime',
            field=models.BigIntegerField(default=1559636041.312554),
        ),
    ]
